/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from "./routes/__root";
import { Route as DownforceImport } from "./routes/downforce";
import { Route as DragImport } from "./routes/drag";
import { Route as IndexImport } from "./routes/index";
import { Route as WingsImport } from "./routes/wings";

// Create/Update Routes

const WingsRoute = WingsImport.update({
  id: "/wings",
  path: "/wings",
  getParentRoute: () => rootRoute,
} as never);

const DragRoute = DragImport.update({
  id: "/drag",
  path: "/drag",
  getParentRoute: () => rootRoute,
} as never);

const DownforceRoute = DownforceImport.update({
  id: "/downforce",
  path: "/downforce",
  getParentRoute: () => rootRoute,
} as never);

const IndexRoute = IndexImport.update({
  id: "/",
  path: "/",
  getParentRoute: () => rootRoute,
} as never);

// Populate the FileRoutesByPath interface

declare module "@tanstack/react-router" {
  interface FileRoutesByPath {
    "/": {
      id: "/";
      path: "/";
      fullPath: "/";
      preLoaderRoute: typeof IndexImport;
      parentRoute: typeof rootRoute;
    };
    "/downforce": {
      id: "/downforce";
      path: "/downforce";
      fullPath: "/downforce";
      preLoaderRoute: typeof DownforceImport;
      parentRoute: typeof rootRoute;
    };
    "/drag": {
      id: "/drag";
      path: "/drag";
      fullPath: "/drag";
      preLoaderRoute: typeof DragImport;
      parentRoute: typeof rootRoute;
    };
    "/wings": {
      id: "/wings";
      path: "/wings";
      fullPath: "/wings";
      preLoaderRoute: typeof WingsImport;
      parentRoute: typeof rootRoute;
    };
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  "/": typeof IndexRoute;
  "/downforce": typeof DownforceRoute;
  "/drag": typeof DragRoute;
  "/wings": typeof WingsRoute;
}

export interface FileRoutesByTo {
  "/": typeof IndexRoute;
  "/downforce": typeof DownforceRoute;
  "/drag": typeof DragRoute;
  "/wings": typeof WingsRoute;
}

export interface FileRoutesById {
  __root__: typeof rootRoute;
  "/": typeof IndexRoute;
  "/downforce": typeof DownforceRoute;
  "/drag": typeof DragRoute;
  "/wings": typeof WingsRoute;
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath;
  to: keyof FileRoutesByTo;
  id: keyof FileRoutesById;
  fileRoutesById: FileRoutesById;
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute;
  DownforceRoute: typeof DownforceRoute;
  DragRoute: typeof DragRoute;
  WingsRoute: typeof WingsRoute;
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DownforceRoute: DownforceRoute,
  DragRoute: DragRoute,
  WingsRoute: WingsRoute,
};

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>();
